# Generated by Django 5.1.3 on 2024-11-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
