# Generated by Django 5.1.3 on 2024-11-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
    ]
