# Generated by Django 5.1.3 on 2024-11-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_employee_birth_date_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('receita', 'Receita'), ('expense', 'Expense')], max_length=10),
        ),
    ]
