# Generated by Django 5.1.3 on 2024-11-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10),
        ),
    ]
